# 주식 업종 코드 정리
FOOD_BEVERAGE = "005"  # 음식료품
TEXTILE_CLOTHING = "006"  # 섬유,의복
PAPER_WOOD = "007"  # 종이,목재
CHEMISTRY = "008"  # 화학
MEDICINE = "009"  # 의약품
NONMETALLIC_MINERAL = "010"  # 비금속광물
STEEL_METAL = "011"  # 철강, 금속
MACHINE = "012"  # 기계
ELECTRICITY_ELECTRONICS = "013"  # 전기,전자
MEDICAL_PRECISION = "014"  # 의료정밀
TRANSPORTATION_EQUIPMENT = "015"  # 운송장비
DISTRIBUTION_INDUSTRY = "016"  # 유통업
ELECTRIC_GAS_INDUSTRY = "017"  # 전기가스업
CONSTRUCTION_INDUSTRY = "018"  # 건설업
TRANSPORTATION_WAREHOUSE = "019"  # 운수창고
TELECOMMUNICATION_INDUSTRY = "020"  # 통신업
